// Generated by Wrangler on Fri May 17 2024 01:15:52 GMT+0900 (Korean Standard Time)
// by running `wrangler types`

interface Env {
	SESSION_PASSWORD: "Ysw2akwpk4WVgmaEv?e,7o_:wnMrQTkq#ZZqLFoYkfLznq#+_F~XP~fx%k*5zpyQLAUXMpZktEprsioaxuibh6ALuPu-=T%%mLB5";
	DB: D1Database;
}
