#:schema node_modules/wrangler/config-schema.json
name = "yonorder-server"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[[ d1_databases ]]
binding = "DB"
database_name = "yonorder"
database_id = "28cc400a-bdae-4e25-82f4-6146f17f1855"

[vars]
SESSION_PASSWORD = 'Ysw2akwpk4WVgmaEv?e,7o_:wnMrQTkq#ZZqLFoYkfLznq#+_F~XP~fx%k*5zpyQLAUXMpZktEprsioaxuibh6ALuPu-=T%%mLB5'
